project:
  type: book
  output-dir: docs

book:
  title: "Statistical Intuition for Modern Biologists"
  author: "Isaac Vock"
  date: "5/7/2024"
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters: 
        - rnaseq.qmd
        - intro2R.qmd
        - probability.qmd
        - modeling.qmd
    - part: methods.qmd
      chapters: 
        - hypothesis.qmd
        - lm.qmd
        - dreduce.qmd
        - cluster.qmd
    - part: pragmatic.qmd
      chapters:
        - bioinfo.qmd
        - finalproject.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
  pdf:
    documentclass: scrreprt

editor: visual

